### PR TITLE
Fix "Not enough memory" error on Windows 7 more.com by setting code page.

### LINKED ISSUE #4593: "Not enough memory" error on Windows and PHP 7.1+
I am getting `Not enough memory.` error immediately on WP CLI launch, outside of WP context altogether.

I seem to get it consistently on PHP 7.1 in my dev stack and clean vanilla download of PHP 7.2

```
C:\server>php --version && php ext/wp-cli.phar

PHP 7.1.1 (cli) (built: Jan 18 2017 18:51:14) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

Not enough memory.
```

```
C:\server>"php72/php" --version && "php72/php" ext/wp-cli.phar

PHP 7.2.0 (cli) (built: Nov 29 2017 00:17:00) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies

Not enough memory.
```

No error on clean vanilla download of PHP 7.0

```
C:\server>"php70/php" --version && "php70/php" ext/wp-cli.phar

PHP 7.0.26 (cli) (built: Nov 22 2017 13:18:45) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

NAME

  wp

DESCRIPTION

  Manage WordPress through the command-line.
...
```

Unaffected by `memory_limit` configuration.

### PR DESCRIPTION
**Pull request by gitlost**
Fixes #4593

Sets code page to 1252 if on Windows < 10 and pager is `more.com` and PHP >= 7.1.

### CODE REVIEW

File: php/commands/help.php [hunk 1]
```diff
@@ -118,6 +118,12 @@ private static function pass_through_pager( $out ) {
 			$pager = Utils\is_windows() ? 'more' : 'less -r';
 		}
 
+		// For Windows 7 need to set code page to something other than Unicode (65001) to get around "Not enough memory." error with `more.com` on PHP 7.1+.
+		if ( 'more' === $pager && defined( 'PHP_WINDOWS_VERSION_MAJOR' ) && PHP_WINDOWS_VERSION_MAJOR < 10 && function_exists( 'sapi_windows_cp_set' ) ) {
+			// Note will also apply to Windows 8 (see http://msdn.microsoft.com/en-us/library/windows/desktop/ms724832.aspx) but probably harmless anyway.
+			sapi_windows_cp_set( 1252 ); // `sapi_windows_cp_set()` introduced PHP 7.1. Code page 1252 is the most used so probably the most compat.
```
Comment (schlessera) [inline php/commands/help.php]: Does it make sense to pick the codepage through an overrideable ENV variable? That way, impacted users can switch if needed.

**Comment by gitlost** [comment]
Cool, will merge as soon as Travis stops messing about. Might create a Windows 8 virtualbox and check it out before release if poss...
