### PR TITLE
Sync package composer repository on install

### LINKED ISSUE #3275: Your configuration does not allow connections to http://wp-cli.org/package-index/packages.json
I would like to install a package. I get this error:
```
Your configuration does not allow connections to http://wp-cli.org/package-index/packages.json
```

I did not change any configuration, so by default wp-cli is configured in a way that leads to a disfunctional package installation system. How can this be changed?

### PR DESCRIPTION
**Pull request by aaemnnosttv**
Right now, older installs of WP-CLI error when trying to install a new package due to the package index url not being updated from http to https.  This fails when composer goes to query the package index over http, since `secure_http` is being set to true (I believe this is also the default now).  Some users may not know how to correct this manually, and they shouldn't really have to.

This PR performs a simple check when preparing to install a package.  If the current package index isn't found in the composer config file, then it will refresh the definition for the package index repository.

fixes #3275

### CODE REVIEW

File: php/commands/package.php [hunk 1]
```diff
@@ -183,6 +183,13 @@ public function install( $args, $assoc_args ) {
 		$json_manipulator->addMainKey( 'name', 'wp-cli/wp-cli' );
 		$json_manipulator->addLink( 'require', $package_name, $version );
 		$json_manipulator->addConfigSetting( 'secure-http', true );
+
+		// If the composer file does not contain the current package index url, refresh the repository definition.
+		if ( false === strpos( $composer_backup, self::PACKAGE_INDEX_URL ) ) {
```
Comment (danielbachhuber) [inline php/commands/package.php]: This is a bit too blunt.

We should specifically check the repository definition, and only replace `http://wp-cli.org/package-index/`

**Comment by danielbachhuber** [comment]
@aaemnnosttv Can you add a functional test case for this?

**Comment by aaemnnosttv** [comment]
I was thinking about that, but I'm not sure what the best way to handle that would be.  I would need to modify the `composer.json` of the wp-cli tests uses.  Can you point me in the right direction there?

**Comment by danielbachhuber** [comment]
> I would need to modify the packages composer.json that the wp-cli tests use. Can you point me in the right direction there?

You could modify the composer.json with `sed`. Here's an example: https://github.com/wp-cli/wp-cli/blob/master/features/core-verify-checksums.feature#L15

**Comment by aaemnnosttv** [comment]
Hey Daniel, see what you think about the test I added.  It's a little more verbose with the scripting in the scenario, but it works.  You have any ideas as to how to clean that up, or you think it's ok?

File: features/package-install.feature [hunk 2]
```diff
@@ -1,5 +1,35 @@
...
+          "wp-cli": {
+            "type": "composer",
+            "url": "http://wp-cli.org/package-index/"
+          }
+        }
+      }
+      """
+    When I run `rm -rf /tmp/wp-cli-package-install-test/ && mkdir /tmp/wp-cli-package-install-test/ && mv composer.json /tmp/wp-cli-package-install-test/`
+    Then the /tmp/wp-cli-package-install-test/composer.json file should exist
+    When I run `WP_CLI_PACKAGES_DIR=/tmp/wp-cli-package-install-test/ wp --info`
```
Comment (danielbachhuber) [inline features/package-install.feature]: Instead of depending on `/tmp/`, can't we just put `WP_CLI_PACKAGES_DIR` in a directory relative to the test directory? This way, we don't have to clean up the temp directory at the end of the test run either.

File: php/commands/package.php [hunk 3]
```diff
@@ -183,6 +183,14 @@ public function install( $args, $assoc_args ) {
 		$json_manipulator->addMainKey( 'name', 'wp-cli/wp-cli' );
 		$json_manipulator->addLink( 'require', $package_name, $version );
 		$json_manipulator->addConfigSetting( 'secure-http', true );
+
+		$composer_backup_decoded = json_decode( $composer_backup, true );
```
Comment (danielbachhuber) [inline php/commands/package.php]: Is it possible to get the value via the `JsonManipulator` class, instead of having to decode the JSON string again?

File: features/package-install.feature [hunk 4]
```diff
@@ -1,5 +1,35 @@
 Feature: Install WP-CLI packages
 
+  Scenario: Install a package with an old package index url in package composer.json
+    Given an empty directory
+    And a composer.json file:
```
Comment (danielbachhuber) [inline features/package-install.feature]: If the package directory is in `package-directory` off the test directory, then you can just place `composer.json` there with:

```
And a package-directory/composer.json file:
```

File: features/package-install.feature [hunk 5]
```diff
@@ -1,5 +1,35 @@
 Feature: Install WP-CLI packages
 
+  Scenario: Install a package with an old package index url in package composer.json
```
Comment (danielbachhuber) [inline features/package-install.feature]: Can we clarify "an old package index url" as "a http package index url"

File: features/package-install.feature [hunk 6]
```diff
@@ -1,5 +1,35 @@
...
+      {
+        "repositories": {
+          "wp-cli": {
+            "type": "composer",
+            "url": "http://wp-cli.org/package-index/"
+          }
+        }
+      }
+      """
+    When I run `rm -rf /tmp/wp-cli-package-install-test/ && mkdir /tmp/wp-cli-package-install-test/ && mv composer.json /tmp/wp-cli-package-install-test/`
```
Comment (danielbachhuber) [inline features/package-install.feature]: If you place the `composer.json` in `package-directory` with ^, this step is unnecessary.

**Comment by danielbachhuber** [comment]
> It's a little more verbose with the scripting in the scenario, but it works. You have any ideas as to how to clean that up, or you think it's ok?

You're headed in the right direction! I've left some comments.

File: php/commands/package.php (hunk 3 above)
Comment (aaemnnosttv) [inline php/commands/package.php]: Nope.  It doesn't even decode it internally, it uses all regex for manipulating it.

File: features/package-install.feature (hunk 5 above)
Comment (aaemnnosttv) [inline features/package-install.feature]: Sounds good 👍

File: features/package-install.feature (hunk 6 above)
Comment (aaemnnosttv) [inline features/package-install.feature]: I think I know what you mean? Next iteration will be much cleaner.

File: features/package-install.feature (hunk 4 above)
Comment (aaemnnosttv) [inline features/package-install.feature]: That's a great idea.  Although, there's really no need to put it into a sub-directory, we can just treat the "empty" directory as the package-directory itself.

**Comment by aaemnnosttv** [comment]
Not sure why this failed...

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

Retry?

**Comment by danielbachhuber** [comment]
> Not sure why this failed...

Do the tests pass locally?

File: features/package-install.feature (hunk 4 above)
Comment (danielbachhuber) [inline features/package-install.feature]: > Although, there's really no need to put it into a sub-directory, we can just treat the "empty" directory as the package-directory itself.

This seems like it may cause problems.

**Comment by aaemnnosttv** [comment]
All of the assertions of the test are passing, but it's just hanging there at the end, which is what happened on Travis too.  Really strange..  any idea why it would be locked up like that?  I've tried it a bunch of different ways but it keeps getting stuck at the end and I have to `ctrl-c` it to stop it, and then it goes to the next scenario.

image

Changing the package directory to a sub directory doesn't change anything either.

You seen anything like that before?

**Comment by danielbachhuber** [comment]
Have you verified the installation process completes successfully?

File: features/package-install.feature [hunk 7]
```diff
@@ -1,5 +1,33 @@
...
+          }
+        }
+      }
+      """
+    When I run `WP_CLI_PACKAGES_DIR=. wp --info`
+    Then STDOUT should contain:
+      """
+      WP-CLI packages dir:	.
+      """
+    When I run `WP_CLI_PACKAGES_DIR=. wp package install runcommand/hook`
```
Comment (danielbachhuber) [inline features/package-install.feature]: Can we include an assertion that the "Updating package index repository URL" string is a part of the output?

**Comment by aaemnnosttv** [comment]
Success!

**Comment by aaemnnosttv** [comment]
Anything more here before we can merge this one?
