### PR TITLE
Issue3832: behat: save verb with regex wrong, missing version checks, needs remote dbhost support

### LINKED ISSUE #3832: behat: save verb  with regex wrong, missing version checks, needs remote dbhost support
retrofitting behat fixes from my repro
- the regex for the behat save verb will technically work but is very poor looking. I added needed whitespace without breaking backwards compat if someone did like the Idonthavewhitespacebetweenthings approach.
- added function to be able to check x.x.x version numbers and then added a behat verb to enable using the function
- added the ability to define a remote db host to use rather than the default (127.0.0.1). It now checks for the RESTFUL_TEST_DBHOST environment variable and uses that host if defined.

None of these fixes break compatibility. They silently enhance the test suite.

### PR DESCRIPTION
**Pull request by diablodale**
Fixes #3832

### CODE REVIEW

File: features/bootstrap/FeatureContext.php [hunk 1]
```diff
@@ -178,6 +178,9 @@ public static function create_cache_dir() {
 	 * @param array $parameters context parameters (set them up through behat.yml)
 	 */
 	public function __construct( array $parameters ) {
+		if ( getenv( 'RESTFUL_TEST_DBHOST' ) ) {
```
Comment (danielbachhuber) [inline features/bootstrap/FeatureContext.php]: Let's rename this to `WP_CLI_TEST_DBHOST`

Comment (diablodale) [inline features/bootstrap/FeatureContext.php]: truetrue. Should then we make the sister code in restful also use WP_CLI_TEST_DBHOST?

Comment (danielbachhuber) [inline features/bootstrap/FeatureContext.php]: > Should then we make the sister code in restful also use WP_CLI_TEST_DBHOST?

Yes, although RESTful CLI will be affected by https://github.com/wp-cli/wp-cli/issues/3826 in that the test suite will be a Composer dependency, instead of copied into place.

Comment (diablodale) [inline features/bootstrap/FeatureContext.php]: done
