### PR TITLE
Use `WP_CLI_FORCE_USER_LOGIN=1` to force `--user=<login>`

### LINKED ISSUE #5706: --user=<user> argument unexpectedly looks up by ID when username is numeric
Hello,

Many commands match username, ID and email automatically for the "user" parameters.

Sometimes users have numeric-only username and wp-cli commands match either the username or the ID incorrectly.

There should be a way to identify the user unequivocally.

Bye,

### PR DESCRIPTION
**Pull request by danielbachhuber**
Also squelches with a warning when there's an ambiguous match.

To be documented with https://github.com/wp-cli/wp-cli/issues/5739

Fixes #5706

### CODE REVIEW

File: php/WP_CLI/Fetchers/User.php [hunk 1]
```diff
@@ -24,8 +25,24 @@ class User extends Base {
...
-			$user = get_user_by( 'id', $arg );
+			$check = get_user_by( 'login', $arg );
+			$user  = get_user_by( 'id', $arg );
+			if ( $check && $user ) {
+				WP_CLI::warning(
+					sprintf(
+						'Ambiguous user match (ID=%d and user_login=%d). Defaulting to ID. Force user_login with WP_CLI_FORCE_USER_LOGIN=1.',
+						$arg,
+						$arg,
+						$arg
```
Comment (schlessera) [inline php/WP_CLI/Fetchers/User.php:42]: I think the message could be phrased a bit clearer. Something like this maybe?
```suggestion
						'Ambiguous user match detected (both ID and user_login exist for identifier "%d"). WP-CLI will default to the ID, but you can make it use the user_login instead with WP_CLI_FORCE_USER_LOGIN=1.',
						$arg,
						$arg
```
(test will need to be adapted as well)

**Review by schlessera — CHANGES_REQUESTED** [review]

**Review by schlessera — APPROVED** [review]

File: php/WP_CLI/Fetchers/User.php (hunk 1 above)
Comment (danielbachhuber) [reply php/WP_CLI/Fetchers/User.php]: Updated with a61e9753
