### PR TITLE
Append uniq id when extracting file from Phar

### LINKED ISSUE #4676: copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied
If wp-cli is running by more than one user on the same server, there are conflicts creating the cacert.pem file in a global tmp directory. Because every instance of wp-cli is creating the same file, without prefixing it. This results in multiple errors like:
```php
PHP Warning:  copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/utils.php on line 29
Warning: copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/utils.php on line 29
PHP Warning:  copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/utils.php on line 29
Warning: copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/utils.php on line 29

PHP Warning:  unlink(/tmp/wp-cli-cacert.pem): Operation not permitted in phar:///usr/local/bin/wp/php/utils.php on line 34
Warning: unlink(/tmp/wp-cli-cacert.pem): Operation not permitted in phar:///usr/local/bin/wp/php/utils.php on line 34
PHP Warning:  unlink(/tmp/wp-cli-cacert.pem): Operation not permitted in phar:///usr/local/bin/wp/php/utils.php on line 34
Warning: unlink(/tmp/wp-cli-cacert.pem): Operation not permitted in phar:///usr/local/bin/wp/php/utils.php on line 34
```

The file should be prefixed with either a random runtime ID or minimum with the user name, which is running the command. But the solution with the user name isn't bomb proof, so I would prefer generating a random runtime ID, which is shared with the different functions inside wp cli using the certificate, as long as the command is running.

Can you take a look into it?
Thanks a lot.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #4676

### CODE REVIEW

File: php/utils.php [hunk 1]
```diff
@@ -24,7 +24,7 @@ function extract_from_phar( $path ) {
 
 	$fname = basename( $path );
 
-	$tmp_path = get_temp_dir() . "wp-cli-$fname";
+	$tmp_path = get_temp_dir() . "wp-cli-$fname-" . uniqid( 'wp-cli-extract-from-phar-', true );
```
Comment (gitlost) [inline php/utils.php]: I think it would be better to do this as
```
get_temp_dir() . uniqid( "wp-cli-extract-from-phar-", true ) . "-$fname";
```
to keep the extension the same.

Comment (danielbachhuber) [reply php/utils.php]: What about:

```
get_temp_dir() . 'wp-cli-' . uniqid( "wp-cli-extract-from-phar-", true ) . "-$fname";
```

Comment (gitlost) [reply php/utils.php]: The `wp-cli-` bit though is covered by the arg to `uniqid()`

Comment (danielbachhuber) [reply php/utils.php]: Ah, I see:

```
local ➜  wordpress-develop git:(master) wp shell
wp> $fname = 'router.php';
=> string(10) "router.php"
wp> 'wp-cli-' . uniqid( "wp-cli-extract-from-phar-", true ) . "-$fname";
=> string(66) "wp-cli-wp-cli-extract-from-phar-5a8b0566008283.78459585-router.php"
```

**Comment by gitlost** [comment]
Ok this is failing due to https://github.com/wp-cli/wp-cli/pull/4613, and this check in `CLI_Command::update()`  at [CLI_Command.php#L325](https://github.com/wp-cli/wp-cli/blob/v1.5.0/php/commands/src/CLI_Command.php#L325) for `WP-CLI version:` (note colon at end). Which answers this question https://github.com/wp-cli/wp-cli/pull/4613#issuecomment-357598216

> I wonder if people use the output from wp cli info for scripting purposes. 

with "Yes! We do!".

Probably better to revert https://github.com/wp-cli/wp-cli/pull/4613 than to modify the check...?

**Comment by schlessera** [comment]
Our own break can be fixed either way. Let's discuss reverting during office hours today.
