### PR TITLE
Ensure cache directories are accessibles

### LINKED ISSUE #5011: Warning: Failed to create directory \'/dev/null/\': mkdir(): File exists
hey,

I have have an app that calls wp-cli. I didn't want it to cache the packages because of some security reasons. WP-CLI attempts to write to dev null

```
putenv("WP_CLI_CACHE_DIR=/dev/null");
putenv("WP_CLI_DISABLE_AUTO_CHECK_UPDATE=1"); // no need to have ext requests.
```

`wp core download --path=/tmp/wp5/users/t1/6/6/4/qs3_1543300866_0664/site/htdocs`;

Error: 

> Downloading WordPress 4.9.8 (en_US)...Warning: Failed to create directory \'\\/dev\\/null\\/\': mkdir(): File exists.md5 hash verified: c4e7d68b5c382fbbaf547f2b2d42c198Success: WordPress downloaded.

```
qs@ubuntu:~$ wp --info
OS:	Linux 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.32-0ubuntu0.16.04.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/qs
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.0.1

```

### PR DESCRIPTION
**Pull request by killua99**
Check Cache file is accesible

Resolve #5011

### CODE REVIEW

File: php/WP_CLI/FileCache.php [hunk 1]
```diff
@@ -314,6 +314,9 @@ public function prune() {
 	 */
 	protected function ensure_dir_exists( $dir ) {
 		if ( ! is_dir( $dir ) ) {
+			if ( preg_match( '{(^|[\\\\/])(\$null|nul|NUL|/dev/null)([\\\\/]|$)}', $dir ) ) {
```
Comment (schlessera) [inline php/WP_CLI/FileCache.php]: Add a comment here to explain what the regex does:
```suggestion
			// Disable the cache if a null device like /dev/null is being used.
			if ( preg_match( '{(^|[\\\\/])(\$null|nul|NUL|/dev/null)([\\\\/]|$)}', $dir ) ) {
```

File: php/WP_CLI/FileCache.php [hunk 2]
```diff
@@ -314,6 +314,9 @@ public function prune() {
...
+				return false;
+			}
```
Comment (schlessera) [inline php/WP_CLI/FileCache.php]: CS: Leave an empty line between two pieces of logic:
```suggestion
			}

```

File: features/cli-cache.feature [hunk 3]
```diff
@@ -26,6 +26,18 @@ Feature: CLI Cache
       wordpress-4.9-en_US.tar.gz
       """
 
+  Scenario: Defining cache directory to an inaccessible directory
```
Comment (schlessera) [inline features/cli-cache.feature]: Rephrase:
```suggestion
  Scenario: Using a null device disables the cache without throwing an error
```

**Comment by schlessera** [comment]
Thanks for the PR, @killua99!
