### PR TITLE
Use custom certificate if provided

### LINKED ISSUE #5111: doesn't honour curl.cainfo setting
We are using a firewall that does Deep Packet Inspection, so it uses an internal custom CA and every client must import this CA to the trusted ca list, or every https request will fail.  
Now when i run:
`wp-cli core download`
i get the error:

**Error: Failed to get url 'https://api.wordpress.org/core/version-check/1.6/?locale=en_US': cURL error 60: Peer's certificate issuer has been marked as not trusted by the user..**

I've dowloaded the offial cacert.pem:
http://curl.haxx.se/ca/cacert.pem
appended our CA, and modified php.ini by adding:
`curl.cainfo = /etc/curl-cacert.pem`

now every php https curl call works good, even curl via command line, but not wp-cli!
with wp-cli I continue to receive the same error, why?
maybe wp-cli dosn't use the curl.cainfo setting?

i've tried even:
`echo "cacert /etc/curl-cacert.pem" >> ~/.curlrc`
but it still doesn't work.

Here it's some info about my envirnment:

OS:     Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64  
Shell:  
PHP binary:     /usr/bin/php  
PHP version:    7.2.16  
php.ini used:   /etc/php.ini  
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli  
WP-CLI vendor dir:      phar://wp-cli.phar/vendor  
WP_CLI phar path:       /tmp  
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:   /root/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.1.0

### PR DESCRIPTION
**Pull request by WhiteWinterWolf**
- PHP setting 'curl.cainfo' enforces the CA file to use,
- Otherwise fallback to system-wide defaults, then use the embedded CA file.

Fixes #5111

### CODE REVIEW

File: php/utils.php [hunk 1]
```diff
@@ -743,36 +743,51 @@ static function ( $matches ) use ( $file, $dir ) {
...
+			return Requests::request( $url, $headers, $data, $method, $options );
+		} catch ( Requests_Exception $ex ) {
+			if ( true !== $options['verify'] || 'curlerror' !== $ex->getType() || curl_errno( $ex->getData() ) !== CURLE_SSL_CACERT ) {
+				throw $ex;
+			}
+
+			// Fallback to the embedded CA file.
+			$cert_path = '/rmccue/requests/library/Requests/Transport/cacert.pem';
+			if ( inside_phar() ) {
+				// cURL can't read Phar archives
```
Comment (schlessera) [inline php/utils.php:769]: WPCS requires ending period for comments:
```suggestion
				// cURL can't read Phar archives.
```

**Review by schlessera — CHANGES_REQUESTED** [review]

**Review by schlessera — APPROVED** [review]

**Comment by schlessera** [comment]
Thanks for the PR, @WhiteWinterWolf !
